### ISSUE TITLE
invalid HTML on the front page

### ISSUE THREAD

**Issue by tetron** [common-workflow-language/cwl-website#99] opened 2022-03-02 19:45 UTC
On the front page, using Firefox "view source" it is highlighting invalid HTML:

line 69: there is a dangling `</nav>` but there is no opening `<nav>`

the features grid has nested anchors (a `<a>` inside another `<a>`)
this seems to be due to using `<h3>` for the box titles, it is inserting `<a href="#open-and-free" class="heading__anchor-symbol">§</a>` 
it probably shouldn't use `<h3>`, just a div with the appropriate styling.

**Comment by tetron** [comment] 2022-03-22 13:34
@lunacodes View source is still showing the dangling `</nav>` on line 80 on the live site

**Comment by mr-c** [comment] 2022-03-22 13:51
See also https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.commonwl.org%2F

**Comment by lunacodes** [comment] 2022-03-24 00:28
> @lunacodes View source is still showing the dangling `</nav>` on line 80 on the live site

@tetron Hmm, so this is a bit of a false flag. The `<nav>` and `<div>` tags are all opened/closed in the correct order. The issue is that Jekyll's rendering doesn't maintain indentation when using an `{% include %}`. So the code's perfectly valid (HTML isn't whitespace-sensitive), it's just rendered sloppily b/c Jekyll is pushing it back to the beginning.

Is there any particular reason to look into it, outside of the validator flagging it? If not, I don't think it's worth looking into. (I already tried a bit yesterday, but Jekyll is stubborn about this behavior).

@mr-c thanks for the list. I'll have a fix for the errors up tonight, except for:

> 5. Error: Bad value https://matrix.to/#/#common-workflow-language_common-workflow-language:gitter.im for attribute href on element a: Illegal character in fragment: # is not allowed.

It's the correct link - so nothing can be done there.

Nos. 9-11: These are all the same error that @tetron and I were discussing above.

**Comment by mr-c** [comment] 2022-03-24 07:26
@lunacodes thanks! Yeah, the w3c validator is quite picky. I wouldn't treat every error it throws as a huge problem, especially if things work. Glad it seems not too difficult to fix the parts it did complain about.

**Closed** 2022-03-31 17:38 UTC
